### ISSUE TITLE
IO.IpcReader and IO.IpcWriter should leave underlying stream open

### ISSUE THREAD

**Issue by sonicmouse** [jacqueskang/IpcServiceFramework#10]
When you construct a new  `IpcReader` or `IpcWriter`, you should instantiate the reader/writer like so:

`_reader = new BinaryReader(stream, Encoding.UTF8, leaveOpen: true);`
and
`_writer = new BinaryWriter(stream, Encoding.UTF8, leaveOpen: true);`

In the host and client, you are creating named pipes with the `using` directive... You are insinuating that the caller is responsible for closing the underlying stream. This is confusing for people who may want to continue to use the named pipe. They won't understand why it has been closed even if they take the instantiation out of the `using`.

This is the line i am talking about:
`using (var server = new NamedPipeServerStream(_pipeName, PipeDirection.InOut, _options.ThreadCount))`

**Comment by jacqueskang** [comment]
Thanks @sonicmouse 
this changes is included in v1.0.3
