### ISSUE TITLE
DefaultValueConverter: Is this a viable option?

### ISSUE THREAD

**Issue by sonicmouse** [jacqueskang/IpcServiceFramework#11]
This isn't an issue as much as a question and/or suggestion:

What if, as a last-ditch effort to convert an object to a specific type, as the last block of code we added this:
```
try
{
	destValue = JsonConvert.DeserializeObject(JsonConvert.SerializeObject(origValue), destType);
	return true;
}
catch (Exception) { }

destValue = null;
return false;
```
You are already tightly coupled with `Newtonsoft.Json`, so this could catch some edge cases (like `enum` and `Guid`, for example).

**Comment by jacqueskang** [comment]
Indeed this is a good suggession. DefaultValueConverter could totally rely on json.net for type conversion. I'll try this, thanks

**Comment by jacqueskang** [comment]
Thanks @sonicmouse 
this changes is included in v1.0.3

**Comment by sonicmouse** [comment]
Thanks for all the work on this project -- I have totally pulled WCF out of my project in favor for your project. Speed has increased 10 fold and memory usage has decreased 10 fold.

**Comment by jacqueskang** [comment]
I'm glad that it helps 😁
