### ISSUE TITLE
Multiple Pipes for Different Contracts in v3

### ISSUE THREAD

**Issue by VaslD** [jacqueskang/IpcServiceFramework#118]
**Describe the bug**

This is either a bug or I do not know how to use the new version (v3) of this library. 😭 

When using v2, I was able to write a single program that handles different (contracted) requests from different processes. I looked at the samples in v3, I thought the new syntax would be as simple. I modified the server sample to:

```csharp
namespace IpcServiceSample.ConsoleServer
{
    internal class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureServices(services => {
                    services.AddScoped<IDummyService, DummyService>()
                            .AddScoped<IInterProcessService, InterProcessService>();
                })
                .ConfigureIpcHost(builder => {
                    builder.AddNamedPipeEndpoint<IDummyService>("1F7CECD3-DFEC-4E20-B0DD-404316E89169")
                           .AddNamedPipeEndpoint<IInterProcessService>("pipeinternal");
                })
                .ConfigureLogging(builder => {
                    builder.SetMinimumLevel(LogLevel.Debug);
                });
    }
}
```

But apparently this does not work. The server didn't respond to requests from `pipeinternal` anymore and all clients on this pipe timed out. (I didn't test the other pipe.)

**To Reproduce**

1. Download [this ZIP](https://github.com/jacqueskang/IpcServiceFramework/files/4666893/IpcServiceFramework.Samples.zip).
2. Compile and run both "Server" and "ConsoleClient".
3. Enter whatever in "ConsoleClient" command prompt window.
4. Nothing happens. (`ReverseString` is not called like before.)

**Expected behavior**

The server handles both `pipeinternal` and `1F7CECD3-DFEC-4E20-B0DD-404316E89169` piped requests as configured using different service classes.

**Screenshots**

None

**Additional context**

If the sample I provided was just wrong, can you add a multi-pipe sample?

**Comment by jacqueskang** [comment]
Thank you @VaslD  for reporting this issue.
