### ISSUE TITLE
[Suggestion] Migrate from Castle.Core to System.Reflection.DispatchProxy

### ISSUE THREAD

**Issue by Lakritzator** [jacqueskang/IpcServiceFramework#150]
**Is your feature request related to a problem? Please describe.**
There is a dependency on a project, Castle.Proxy, which is not bad but I believe it makes more sense to stick with the bare functionality of, as this might give better support on the long run for features that .NET 5 bring.

**Describe the solution you'd like**
Migrate to [System.Reflection.DispatchProxy](https://www.nuget.org/packages/System.Reflection.DispatchProxy)

**Describe alternatives you've considered**
Ignore that Castle.Proxy is used, live with it. 🤷‍♂️ 

**Additional context**
I'd be more than happy to have a go, just wanted to ping to see if you would be interested in a PR.
One warning though, although I know my way around DispatchProxy, I currently seem to get tied up in to much stuff,
I didn't have a detailed look at this library, but it was on my list of possible solutions for having a new instance of an application talk to the already running instance, and this was discussed here: https://github.com/dapplo/Dapplo.Microsoft.Extensions.Hosting/pull/11

I might also have misunderstood your usage, I only took around 10 minutes going through your code...

**Comment by jorisvergeer** [comment]
@Lakritzator I gave it a go.

**Comment by Lakritzator** [comment]
@jorisvergeer I hope I still get 5% of the credit, but great work 👍

**Comment by jorisvergeer** [comment]
@Lakritzator I would give you more credit than 5 percent. It was your solution after all. 

And I learned something new :smile:
