### ISSUE TITLE
TCP connections prematurely dispose of the underlying Socket

### ISSUE THREAD

**Issue by spaceisfun** [jacqueskang/IpcServiceFramework#158]
**Describe the bug**
TCP connections prematurely dispose of the underlying Socket without creating a new TcpClient

**To Reproduce**
1. Edit src\JKang.IpcServiceFramework.TcpTests\HappyPathTest.cs, adding a second InvokeAsync call

        [Theory, AutoData]
        public async Task HappyPath(string input, string expected)
        {
            _serviceMock
                .Setup(x => x.StringType(input))
                .Returns(expected);

            string actual = await _client
                .InvokeAsync(x => x.StringType(input));

            Assert.Equal(expected, actual);

            // Execute the Host method again to validate the socket isn't improperly disposed
            actual = await _client
                .InvokeAsync(x => x.StringType(input));
        }

2. Run the test
3. You will hit the following exception

Message: 
    System.ObjectDisposedException : Cannot access a disposed object.
    Object name: 'System.Net.Sockets.Socket'.
  Stack Trace: 
    Socket.BeginConnect(IPAddress address, Int32 port, AsyncCallback requestCallback, Object state)
    TcpClient.BeginConnect(IPAddress address, Int32 port, AsyncCallback requestCallback, Object state)
    <>c.<ConnectAsync>b__27_0(IPAddress targetAddess, Int32 targetPort, AsyncCallback callback, Object state)
    TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
    TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
    TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
    TcpClient.ConnectAsync(IPAddress address, Int32 port)
    TcpIpcClient`1.ConnectToServerAsync(CancellationToken cancellationToken) line 27
    IpcClient`1.GetResponseAsync(IpcRequest request, CancellationToken cancellationToken) line 136
    IpcClient`1.InvokeAsync[TResult](Expression`1 exp, CancellationToken cancellationToken) line 49
    HappyPathTest.HappyPath(String input, String expected) line 44
    --- End of stack trace from previous location where exception was thrown ---

**Expected behavior**
A second call to InvokeAsync succeeds.

**Comment by spaceisfun** [comment]
Proposed fix: https://github.com/jacqueskang/IpcServiceFramework/pull/159

**Comment by jacqueskang** [comment]
Thank you @spaceisfun!
