### ISSUE TITLE
feature: Support manually created IpcRequests to allow IPC without needing dynamic code generation

### ISSUE THREAD

**Issue by spaceisfun** [jacqueskang/IpcServiceFramework#165]
**Is your feature request related to a problem? Please describe.**
The current IPC code requires dynamic code generation, which is not supported on .NET Native. Adding new InvokeAsync APIs to allow the Client to pass manually created IpcRequest objects would let you use this IPC solution on .NET Native.

**Comment by jacqueskang** [comment]
Thank you again!
