### ISSUE TITLE
feature: Support passing Types as 'simple' names instead of Type objects, to allow for version mismatches between Client & Host assemblies

### ISSUE THREAD

**Issue by spaceisfun** [jacqueskang/IpcServiceFramework#167]
**Is your feature request related to a problem? Please describe.**
Currently, the IpcRequest includes System.Type objects representing the Type of the parameters passed in. This causes the method lookup on the Host to fail if the Host is using a different version of the objects than the Client, as the Host's GetUnambiguousMethod() code looks for exact Type matches. 

This feature would allow the Client to pass the parameter Types as string Names instead of Type objects, allowing for a looser match.

**Comment by jacqueskang** [comment]
Thank you @spaceisfun this is really nice!
I even think this option should be enabled by default.
