### ISSUE TITLE
[Feature Request] supporting graceful shutdown.

### ISSUE THREAD

**Issue by itn3000** [jacqueskang/IpcServiceFramework#30]
Currently, IIpcServiceHost has only `Run()` method, and there is no way to stop running.
It may be the cause of unexpected exception when shutdown( or reboot) the service.

so I suggest adding `Run(CancellationToken ct)` or `Stop()` to IIpcServiceHost interface.

**Comment by jacqueskang** [comment]
Thanks for your suggestion.

**Comment by jacqueskang** [comment]
Resolved in v2.0.1
