### ISSUE TITLE
Support for generic type parameter

### ISSUE THREAD

**Issue by marius-stanescu** [jacqueskang/IpcServiceFramework#32]
I am trying to pass a type as parameter, but when I call `InvokeAsync` on the Ipc service client it throws the exception: 

> System.IO.Exception: Pipe is broken

Here's my code:

```c#
public interface IEventPublisher
{
    void Publish<T>(T eventMessage);
}
```

```c#
public class EventPublisher : IEventPublisher
{
    public void Publish<T>(T eventMessage)
    {
        //publish event to subscribers
    }
}
```

```c#
var ipcServiceClient = new IpcServiceClientBuilder<IEventPublisher>()
    .UseNamedPipe(Constants.EventsPipeName)
    .Build();

await ipcServiceClient
    .InvokeAsync(x => x.Publish(new DiskFullEvent(disk)))
    .ConfigureAwait(false);
```

**Comment by jacqueskang** [comment]
For the time being I'm only adding minumum generic parameter support.
It should work with `Publish<T>(T message)` but not something like `Publish<T>(GenericMessage<T> message)`
Supprting all kinds of generic seems to be a big work for me.

**Comment by marius-stanescu** [comment]
@jacqueskang you said `Publish<T>(T message)` should work, but it doesn't. It throws the following error:

> System.IO.IOException: Pipe is broken.
> at System.IO.Pipes.PipeStream.CheckWriteOperations()
> at System.IO.Pipes.PipeStream.Flush()
> at JKang.IpcServiceFramework.IpcServiceClient`1.GetResponseAsync(IpcRequest request)
> at JKang.IpcServiceFramework.IpcServiceClient`1.InvokeAsync(Expression`1 exp)

**Comment by jacqueskang** [comment]
Hi @marius-stanescu, what is the actual type T you are using please?

**Comment by marius-stanescu** [comment]
public class DiskFullEvent
{
    public DiskFullEvent(int diskId)
    {
        DiskId = diskId;
    }

    public int DiskId { get; }
}

**Comment by marius-stanescu** [comment]
Hey, sorry, but I didn't see you updated the NuGet package and I was still running on a previous version (2.0.0.2). After updating the package to the latest version (2.1.2) it started working. So thanks!
