### ISSUE TITLE
Very good implemetation of IPC Server for .NET Core

### ISSUE THREAD

**Issue by guehmann** [jacqueskang/IpcServiceFramework#55]
I use your application (source with  in a normal .net core console application with server and client). It works  really well. Now i want to implement it in a windows service (asp.net core service) with HostBuilder like this...

       static async Task Main(string[] args)
        {
            Console.WriteLine(await FileInfoHelper.GetProductInformationText());

            await new HostBuilder()
                .ConfigureServices((hostContext, services) => { services.AddHostedService<TerminalService>(); })
                .RunConsoleAsync();
        }

And in the service like:
        public Task StartAsync(CancellationToken cancellationToken)
        {
            try
            {
                Console.WriteLine("Anytime Dispatcher Services are starting...");

                var builder = new ConfigurationBuilder()
                    .SetBasePath(Directory.GetCurrentDirectory())
                    .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true);
                IConfigurationRoot configuration = builder.Build();

                var settings = configuration.GetSection("Connection").Get<IPCServerConfiguration>();
                Console.WriteLine($"Listening on ip address {IPAddress.Loopback.ToString()} port {settings.Port} for endpoint {settings.Endpoint}.");

                IServiceCollection services = ConfigureServices(new ServiceCollection());
                new IpcServiceHostBuilder(services.BuildServiceProvider())
                    .AddTcpEndpoint<IComputingService>(name: settings.Endpoint, ipEndpoint: IPAddress.Loopback, port: settings.Port)
                    .Build()
                    .Run();
            }
            catch (Exception e)
            {
                LoggingHelper.Error($"IPC Server Test Instance could not start.");
                LoggingHelper.Error($"Error: {e.Message}");

                throw e;
            }

If i try to look if a port is listening with netstat -ano | findstr portnumber i get a good result,
but I think the service is blocking. Bekause CTRL-C is not working on the host service.

Perhaps you have any idea or sugestion for me.

Thanks in advance.
Best regards Jens

**Comment by guehmann** [comment]
Hi Jacques,

thanks for your reply.
I tried it and now it's working for me. Also no problem with CTRL+C issue.

Regards
Jens

**Comment by jacqueskang** [comment]
Great
