### ISSUE TITLE
Eta for version 2.1.3 on nuget

### ISSUE THREAD

**Issue by adospace** [jacqueskang/IpcServiceFramework#56]
Sorry to bother, may I ask if you are planning to publish the latest build on nuget in the near future?

**Comment by jacqueskang** [comment]
@adospace, The next release will be 2.2.0 and I'm only waiting to include SSL support proposed by #51.
But I don't know when gsuberland will update the PR, I can move that to 2.3.0 and publish a new release if you need it.

**Comment by adospace** [comment]
@jacqueskang well, yes, I actually need it for my project so it would be greatly appreciated. 
Of course, take your time.

**Comment by jacqueskang** [comment]
2.2.0 nuget packages are published
