### ISSUE TITLE
How to use this library in HostBuilder

### ISSUE THREAD

**Issue by maksim789456** [jacqueskang/IpcServiceFramework#58]
Hello to all.
Could you tell me how to properly integrate the server into my HostBuilder?

**Screenshots**
![screenshot_1](https://user-images.githubusercontent.com/8225008/50343177-63fb4180-053f-11e9-87a2-f79f381b1f82.png)

**Comment by jacqueskang** [comment]
Hi @maksim789456,

Sorry but IPC service cannot be integrated in HostBuilder yet. It uses its own host builder at the time being `IpcServiceHostBuilder`

Actually the project was started before Generic Host was released and I was planning to migrate to GenericHost. 

But at the time being you have to figure out a walkaround, maybe checkout 
https://github.com/jacqueskang/IpcServiceFramework/blob/develop/src/IpcServiceSample.WebServer/Program.cs

**Comment by maksim789456** [comment]
> Hi @maksim789456,
> 
> Sorry but IPC service cannot be integrated in HostBuilder yet. It uses its own host builder at the time being `IpcServiceHostBuilder`
> 
> Actually the project was started before Generic Host was released and I was planning to migrate to GenericHost.
> 
> But at the time being you have to figure out a walkaround, maybe checkout
> https://github.com/jacqueskang/IpcServiceFramework/blob/develop/src/IpcServiceSample.WebServer/Program.cs

It is sad
Now I will try to create a separate service and place the server there.

**Comment by jacqueskang** [comment]
Seems like you can wrap IpcServiceHostBuilder in a IHostedService implementation like
```
    class IpcHostedService : IHostedService
    {
        private readonly IIpcServiceHost _host;

        public IpcHostedService(IServiceProvider sp)
        {
            _host = new IpcServiceHostBuilder(sp)
                .AddTcpEndpoint<IYourService>("yourendpoint", IPAddress.Loopback, 45684)
                .Build();
        }

        public Task StartAsync(CancellationToken cancellationToken) => _host.RunAsync(cancellationToken);

        public Task StopAsync(CancellationToken cancellationToken) => throw new NotImplementedException();
    }
```
Then add `services.AddHostedService<IpcHostedService>();` in `ConfigureServices()`

**Comment by maksim789456** [comment]
Did not work out
![image](https://user-images.githubusercontent.com/8225008/50345369-4383b500-0548-11e9-8f3a-9e8086e9aa2b.png)

**Comment by jacqueskang** [comment]
You also need to call services.AddIpc() in ConfigureServices() 
```
    services.AddIpc(builder => builder.AddService<IYourService, YourService>());
```

**Comment by maksim789456** [comment]
> You also need to call services.AddIpc() in ConfigureServices()
> 
> ```
>     services.AddIpc(builder => builder.AddService<IYourService, YourService>());
> ```

Oh yeah, I forgot ... -_-

**Comment by maksim789456** [comment]
Little problem...
Service took control and does not give it away
![image](https://user-images.githubusercontent.com/8225008/50346069-9cece380-054a-11e9-8643-8c07abf5bd0f.png)

**Comment by jacqueskang** [comment]
I have no idea... possible to log more details?

**Comment by jacqueskang** [comment]
What exactly is the issue please? The server cannot be stopped or your service method hangs?

**Comment by maksim789456** [comment]
> What exactly is the issue please? The server cannot be stopped or your service method hangs?

Management remains with the ipc service and the application does not start up to the end.
For good management should go to HostBuilder and he will run the application to the end.

If you turn off the ipc service, HostBuilder starts the application normally.
![image](https://user-images.githubusercontent.com/8225008/50347724-10452400-0550-11e9-9c05-424031a5d9b3.png)

**Comment by maksim789456** [comment]
Judging from the dotTrace data
HostBuilder is waiting for Ipc service
What somehow should not happen...
![image](https://user-images.githubusercontent.com/8225008/50348189-74b4b300-0551-11e9-8710-de8b80975dbf.png)

**Comment by maksim789456** [comment]
![image](https://user-images.githubusercontent.com/8225008/50348502-60bd8100-0552-11e9-973e-f9d922e235d9.png)
This is a full tracking by StartAsync

**Comment by jacqueskang** [comment]
I guess the problem might be related to this line:
```csharp
public Task StartAsync(CancellationToken cancellationToken) => _host.RunAsync(cancellationToken);
```
Currently IIpcServiceHost doesn't support StartAsync() and StopAsync(). It only has RunAsync() which is blocking if be awaited.
So maybe you can try this:
```csharp
    class IpcHostedService : IHostedService
    {
        private readonly CancellationTokenSource _source;
        private readonly IIpcServiceHost _host;

        public IpcHostedService(IServiceProvider sp)
        {
            _source = new CancellationTokenSource();
            _host = new IpcServiceHostBuilder(sp)
                .AddTcpEndpoint<IComputingService>("yourendpoint", IPAddress.Loopback, 45684)
                .Build();
        }

        public Task StartAsync(CancellationToken cancellationToken)
        {
            _host.RunAsync(_source.Token);
            return Task.CompletedTask;
        }

        public Task StopAsync(CancellationToken cancellationToken)
        {
            _source.Cancel();
            return Task.CompletedTask;
        }
    }
```

**Comment by maksim789456** [comment]
@jacqueskang, thank you very much! ^_^
It is working(or almost):
![image](https://user-images.githubusercontent.com/8225008/50349935-d1669c80-0556-11e9-89c4-3d0f558bf891.png)
But I can solve it myself
(although I will not give up on helping)

**Comment by jacqueskang** [comment]
Your are welcome!
