### ISSUE TITLE
Handle connection errors (eg. timeouts)

### ISSUE THREAD

**Issue by Anders2020** [jacqueskang/IpcServiceFramework#62]
If you create a client and try to connect an server that is offline there is no error generated like timeout error. And there is no access to the underlying task produced from "ConnectToServerAsync".
the client will simply freeze.

**Comment by Anders2020** [comment]
""ConnectToServerAsync" calls the "await stream.ConnectAsync". This produces a Task which is being discarded. This task should have the underlying timeout error but is inaccessible. Am using NamedPipes implementation.

**Comment by pablocar80** [comment]
I do get timeout errors as expected. I'm using named pipes.

**Comment by large** [comment]
I use named pipes and when server is offline the client never returns.
Hopefully it will be fixed, this library is easy and great to use!
