### ISSUE TITLE
Exception on receiving larger message

### ISSUE THREAD

**Issue by Letalis82** [jacqueskang/IpcServiceFramework#63]
On a request from my client to my server project that returns an answer with a size of a few MB's an exception is sometimes thrown:
Newtonsoft.Json.JsonReaderException: 'Unterminated string. Expected delimiter: ". Path 'MyDataObject, line 1, position 3649521.'

I use the following code to setup my service:
`new IpcServiceHostBuilder(services.BuildServiceProvider())
                        .AddTcpEndpoint<IServiceContract>(name: "ServiceName", ipEndpoint: IPAddress.Any, port: 9000)
                        .Build()
                        .Run();`
 
For the client:
`IpcServiceClient<IServiceContract> myServiceClient = new IpcServiceClientBuilder<IServiceContract>()
                .UseTcp(IPAddress.Parse(127.0.0.1), 9000)
                .Build();`

The exception happens in the client code:
`var myResult = await myServiceClient.InvokeAsync(m => m.MyFunction("A param"));`

Is there a bug in my code or do I miss a setting to set the message size?

**Comment by jacqueskang** [comment]
Hi @Letalis82,

The default mesage serializer relies on Newtonsoft.Json for deserialization and I didn't find any artifical size limit that is imposed by Newtonsoft.Json.

Could you please provide more details regarding the issue please?

**Comment by Letalis82** [comment]
Hi @jacqueskang 

The problem is when my message contract contains a byte[] (or a byte[] that is converted to a string). I'll receive errors like this:
![image](https://user-images.githubusercontent.com/45654542/55413883-79363200-556a-11e9-9679-95747145bd28.png)

What other info can help you?

**Comment by jacqueskang** [comment]
Otherwise you can create a custom implementation of IIpcMessageSerializer interface by copying 
https://github.com/jacqueskang/IpcServiceFramework/blob/develop/src/JKang.IpcServiceFramework.Core/Services/DefaultIpcMessageSerializer.cs

Then configure your client to use this custom serializer this way:
```csharp
IpcServiceClient<IServiceContract> myServiceClient = new IpcServiceClientBuilder<IServiceContract>()
    .WithIpcMessageSerializer(new YourCustomSerializer())
    .UseTcp(IPAddress.Parse(127.0.0.1), 9000)
    .Build();
```

Then you can debug into the serializer to see why exactly the json deserialization failed

**Comment by Letalis82** [comment]
It looks like the Json serializer is quite embedded in the source. 

When I use a copy of the DefaultIpcMessageSerializer I got exactly the same (and unfortunately useless) error.

Then I started to use your code as my test setup and tested with your ConsoleServer & Client projects.
I tried to use the following alternatives as serializers:
MessagePack / Zerro formatter 
(both give me the same error) The can not handle the object type in there serialization.

Microsoft.Xml Serializer:
There is an error in XML document (1, 1)

Salar.Bois
Exception in file IpcReader.cs
public async Task<IpcResponse> ReadIpcResponseAsync(CancellationToken cancellationToken = default(CancellationToken))

Looks like with every other serializer the response here is 150bytes that cannot be serialized back to IpcResponse.

Do you have an example for me where an other serializer is working?

**Comment by hoochharp** [comment]
There is a bug in the IpcReader where only one attempt is made to read all of the data on the stream.  You must continue reading until the data length is 0 (end of stream of the socket was shut down)  Here is the corrected code which also tests that the initial header is exactly 4 bytes long.

       private async Task<byte[]> ReadMessageAsync(CancellationToken cancellationToken)
        {
            int headerLength = await _stream.ReadAsync(_lengthBuffer, 0, _lengthBuffer.Length, cancellationToken);

            if (headerLength != 4)
            {
                throw new ArgumentOutOfRangeException($"Header length must be 4 but was {headerLength}");
            }

            int expectedLength      = _lengthBuffer[0] | _lengthBuffer[1] << 8 | _lengthBuffer[2] << 16 | _lengthBuffer[3] << 24;
            var bytes               = new byte[expectedLength];
            var totalBytesReceived  = 0;
            var remainingBytes      = expectedLength;

            using (MemoryStream ms = new MemoryStream())
            {
                while (totalBytesReceived < expectedLength)
                {
                    int dataLength = await _stream.ReadAsync(bytes, 0, remainingBytes, cancellationToken);

                    if (dataLength == 0)
                    {
                        break;             // end of stream or stream shut down.
                    }

                    ms.Write(bytes, 0, dataLength);
                    totalBytesReceived += dataLength;
                    remainingBytes -= dataLength;
                }

                bytes = ms.ToArray();
            }

            if (totalBytesReceived != expectedLength)
            {
                throw new System.ArgumentOutOfRangeException($"Data length must be {expectedLength} but was {totalBytesReceived}");
            }

            return bytes;
        }

**Comment by jacqueskang** [comment]
I'm able to reproduce this bug with a test

**Comment by jacqueskang** [comment]
And the test is passing with the fix you provided, @hoochharp 
I'll integrate, thanks you!
