### ISSUE TITLE
Duplex Service

### ISSUE THREAD

**Issue by intemedic** [jacqueskang/IpcServiceFramework#66]
**Is your feature request related to a problem? Please describe.**
I'm using this framework and trying to implement a duplex service.

**Describe the solution you'd like**
Is there a plan to support duplex service? (Or is it already supported, just I didn't see?)

(A duplex service contract is a message exchange pattern in which both endpoints can send messages to the other independently. [WCF supports duplex service](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/duplex-services).)

**Describe alternatives you've considered**
I'm aware that I can establish another connection with the server/client roles flipped. However maintaining an additional connection for each client is cumbersome and less graceful.

**Additional context**
None yet!

_(edit: fix typo)_

**Comment by danielmeza** [comment]
this can be done by hosting a shading pipe in the client git a Guid for every duplex service, the use TaskCompletionSource to sync the calls

**Comment by danielmeza** [comment]
@jacqueskang this can help https://www.codeproject.com/Articles/1179195/Full-Duplex-Asynchronous-Read-Write-with-Named-Pip

**Comment by jacqueskang** [comment]
Sorry guys for being so late. Due to limited energy I want to keep this project simple.
I'm not planning to implement duplex support
