### ISSUE TITLE
How to handle exceptions in server?

### ISSUE THREAD

**Issue by pablocar80** [jacqueskang/IpcServiceFramework#67]
Hello! In WCF, the way to handle errors in the server is to raise FaultException. Throwing this exception won't crash the server and the exception is sent to the client to handle. This simplifies the design of the interface because there is no need to return error codes. Is there an equivalent to FaultException here?

**Comment by pablocar80** [comment]
@jacqueskang when I code the server to throw exceptions with specific messages, the client gets instead a generic exception that says:

> Internal server error: Exception has been thrown by the target of an invocation.

Is it possible to have the client receive the information that's in the original exception thrown by the client?

(Also, in some situations you would want to never send exception information to the client for security reasons, so I see why this shouldn't be the default behavior).

So maybe we could send FaultExceptions and derived exceptions to the client, and generic exceptions otherwise?

**Comment by jacqueskang** [comment]
@pablocar80  I realized this issue is already resolved by PR #85

Please reopen if you disagree.
