### ISSUE TITLE
implement async ConfigureAwait(false)

### ISSUE THREAD

**Issue by toneo** [jacqueskang/IpcServiceFramework#71]
We are switching over our project to .NET Core and as a result want to switch to your great IPC library.
Unfortunately, we were getting a whole bunch of deadlocks in the async code.
I went ahead and grabbed the source code, and I added .ConfgureAwait(false) to all the async function calls in your library and this takes care of the problem.

Microsoft recommends using configureawait(false) in library code whereever possible
https://msdn.microsoft.com/en-us/magazine/jj991977.aspx

If I submit my changes as a pull request are you happy to apply them for a new version?

**Comment by jacqueskang** [comment]
@toneo Yes a PR would be nice, thank you!

**Comment by toneo** [comment]
Done! please take a look
https://github.com/jacqueskang/IpcServiceFramework/pull/72
