### ISSUE TITLE
Add support for interfaces and derived classes

### ISSUE THREAD

**Issue by pablocar80** [jacqueskang/IpcServiceFramework#75]
I have an operation method called "LoadSettings" that returns a list of objects. These objects are instances of different classes, they all implement a common interface and derive from a base abstract class.

However, it's not currently possible to return this list:
- If the server sends a list of X where X is an interface, the client yields an exception that X is an interface and thus cannot be instantiated.
- If the server sends a list of Y where Y is an abstract class, we get the same error that an abstract class cannot be instantiated.

**Is your feature request related to a problem? Please describe.**
Yes, migrating from WCF and this isn't supported.

**Describe the solution you'd like**
This is only a suggestion: WCF uses the class attributes 'KnownType' to be able serialize collections of yet-to-be-known classes. Example:

```
    [DataContract]
    [KnownType(typeof(SiteRecord))]
    [KnownType(typeof(RedirectRecord))]
    public abstract class BaseBucket : IBucket
    {
        [DataMember]
        public string Name { get; set; }

        [DataMember]
        public bool Enabled { get; set; }
...
}
```

**Describe alternatives you've considered**
In order to avoid this issue, I will extend my interfaces so they return collections of specific types. For example, instead of returning a collection of 'Animal', I will have one collection for 'Tiger', one for 'Zebra', and so on.

**Additional context**
The exact error message is 'Could not create an instance of type X. Type is an interface or abstract class and cannot be instantiated.'

**Comment by jacqueskang** [comment]
Indeed this is a good suggestion. Thanks

**Comment by maksim789456** [comment]
Hello everyone, I created some attribute to work around this problem. At the moment it is applicable only to interfaces, but it already works. It is certainly not as perfect as compared to the wcf attribute.
p.s. Soon we will create a RP with these changes.
![изображение](https://user-images.githubusercontent.com/8225008/59399390-e3f2bd80-8da4-11e9-85cf-5c28adc2150c.png)

**Comment by pablocar80** [comment]
@maksim789456 when would you need this in interfaces?

**Comment by jacqueskang** [comment]
For the time being I leverage Json.net's `TypeNameHandling.Objects` to handle abstraction which seems to be a quick win.
