### ISSUE TITLE
Open host with non-blocking code

### ISSUE THREAD

**Issue by pablocar80** [jacqueskang/IpcServiceFramework#78]
**Is your feature request related to a problem? Please describe.**
The method Run() starts the server and blocks until it's terminated. Similarly, the RunAsync() blocks until shutdown if awaited. Sometimes it's desirable to start a server and keep executing.
Examples:
a) we're opening more than 1 server to listen
b) we have code that needs to be executed AFTER the server started listening (and an example here is to have a central server that spawns a new process that will connect to it).

**Describe the solution you'd like**
Have the Open() method. Instead of returning on shutdown, it returns after it successfully started listening. If listening fails (e.g. cannot bind to port) it raises an exception.

**Describe alternatives you've considered**
I am currently using RunAsync from a synchronous method. This accomplishes the non-blocking part. However, if opening fails, the code won't realize that and the exception will be discarded behind the scenes.

**Comment by maksim789456** [comment]
I understand that this is due to the fact that IpcServiceHost is not asynchronous in the RunAsync method, and the code is just waiting for all endpoints to complete.

If we rewrite the startup code a bit, we get control back.
```csharp
public async Task RunAsync(CancellationToken cancellationToken = default(CancellationToken))
{
    foreach (IpcServiceEndpoint endpoint in _endpoints)
    {
        await Task.Factory.StartNew(async () =>
        {
            _logger.LogDebug($"Starting endpoint '{endpoint.Name}'...");

            cancellationToken.Register(() => { _logger.LogDebug($"Stopping endpoint '{endpoint.Name}'..."); });

            await endpoint.ListenAsync(cancellationToken).ContinueWith(
                _ => { _logger.LogDebug($"Endpoint '{endpoint.Name}' stopped."); }, cancellationToken);
        }, cancellationToken);
    } 
}
```
@jacqueskang please rewrite this method!

**Comment by jacqueskang** [comment]
v3 will leverage [BackgroundService](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.backgroundservice?view=dotnet-plat-ext-3.1) to resolve this issue.
