### ISSUE TITLE
Strong Name Sign Assembly

### ISSUE THREAD

**Issue by adamdriscoll** [jacqueskang/IpcServiceFramework#81]
**Is your feature request related to a problem? Please describe.**
I want to use this package in a Visual Studio extension but it requires that the assembly is strong name signed.

**Describe the solution you'd like**
I would like to either have this package signed or produce a separate package that is signed. 

**Describe alternatives you've considered**
I'm currently submoduling this in my repo and signing it myself.

**Comment by atomaras** [comment]
Have the same issue when trying to reference from an ASP.NET project

> Could not load file or assembly 'JKang.IpcServiceFramework.Client, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
