### ISSUE TITLE
Add IPC Deprecated?

### ISSUE THREAD

**Issue by TonyValenti** [jacqueskang/IpcServiceFramework#84]
Why is AddIPC Deprecated?  What should I use instead?

**Comment by TonyValenti** [comment]
Also, related to this, can you please add a property to the options that allows me to specify the PipeSecurity options for the server?  To give you some context:

We have a library that:
* Uses Remoting over Named Pipes
* Uses .NET Framework
* Invokes methods in a separate process _under a different user account_

We are porting to .NET Core and want to use IpcServiceFramework.
Currently IpcServiceFramework does not expose the PipeSecurity options.  This means that only the user that created the pipe server can connect to it.

Can you please add a property to the options that allows me to specify the PipeSecurity options for the server?

**Comment by maksim789456** [comment]
I do not recommend using this library. The author scored on the development. My RP with changes has been open for 4 months. See #82

**Comment by dynamoRando** [comment]
Is this project still being worked? I am on mobile and was debating on posting an issue with a TCP pipe but it looks like the project is no longer being maintained.

**Comment by jacqueskang** [comment]
Guys, for personal reason I do have no time to maintain this project since a few months

Meantime .NET Core 3.0 is released with gRPC feature, which I think is probably a alternative.
https://docs.microsoft.com/en-us/aspnet/core/grpc/?view=aspnetcore-3.0

**Comment by dynamoRando** [comment]
Hey no problem, just checking in. Enjoy!

**Comment by jacqueskang** [comment]
I got some time to update this project to v3 based on .NET Core 3.1
