### ISSUE TITLE
Latest 2.3.0 introduces timeout bug in NamedPipes connect

### ISSUE THREAD

**Issue by cklutz** [jacqueskang/IpcServiceFramework#87]
**Describe the bug**
Using NamedPips, the connection attempt always lasts at max 3 seconds. In previous versions the connection attempt was not constraint with an (arbitrary/fixed) timeout.
This causes all clients that take - whatever the reason - longer than 3 seconds to connect to abort with a `TimeoutException`.

**To Reproduce**
Write a test client and server where the connection attempt takes more time than 3 seconds.

**Expected behavior**
No arbitrary/fixed timeout should be enforced on connecting to a server. It *could* be beneficial to provide extra timeout options to configure the stack, but this is not part of this bug report.

**Additional context**
It looks as this bug was introduced (accidentally?) by PR #72, see https://github.com/anthonypcole/IpcServiceFramework/blob/16c1c3768f9916df7af65f9f397a1887511b8680/src/JKang.IpcServiceFramework.Client/NamedPipe/NamedPipeIpcServiceClient.cs#L24. Especially the `(int)TimeSpan.FromSeconds(3).TotalMilliseconds` which has been added as timeout parameter to the `ConnectAsync()` operation in this change.

![image](https://user-images.githubusercontent.com/7589638/71513383-6010a680-289a-11ea-9781-ddf2942e0903.png)

I would guess this code is a leftover from some testing efforts and should be removed, i.e. simply remove the first parameter to `ConnectAsync()` in the above mentioned line.

**Comment by jacqueskang** [comment]
Thank you. Resolved in 2.3.1
